void main () {

    try {
        stoi("1");
    }
    catch{
        print("ERROR");
    }

}