void f (){
    try {
        stoi("abc");
    }
    catch{
        print("ERROR");
    }

}



void main () {
    f();
}