// This file is to test the while structure within a try catch block, it should not produce an error and output "1111"

void main () {

    try {
        int i = 0;
        string z = "1";
        while (i < 3){
            z = z + "1";
            i = i + 1;
        }
        print(stoi(z));

        print("\n");

        print("DONE");
    }
    catch{
        print("ERROR");
    }
}